<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('images')->insert(
            [
                [
                    'path' => 'attractions/1.jpg',
                    'imageable_id' => '1',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/2.png',
                    'imageable_id' => '1',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/dufan.jpg',
                    'imageable_id' => '1',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/bromo.jpg',
                    'imageable_id' => '2',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/kuta.png',
                    'imageable_id' => '3',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/kuta.jpg',
                    'imageable_id' => '3',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/Kuta-Beach-Surfing.jpg',
                    'imageable_id' => '3',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/Kuta-beach-Sunset.jpg',
                    'imageable_id' => '3',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/borobudur-temple.jpg',
                    'imageable_id' => '4',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/borobudur-temple-2.jpg',
                    'imageable_id' => '4',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/borobudur-temple-3.jpg',
                    'imageable_id' => '4',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/borobudur-temple-4.jpg',
                    'imageable_id' => '4',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/tana-toraja.jpg',
                    'imageable_id' => '5',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/tana-toraja-2.jpg',
                    'imageable_id' => '5',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/tana-toraja-3.jpg',
                    'imageable_id' => '5',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/lake-toba.jpg',
                    'imageable_id' => '6',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/lake-toba-2.jpg',
                    'imageable_id' => '6',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/lake-toba-3.jpg',
                    'imageable_id' => '6',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/lake-toba-4.jpg',
                    'imageable_id' => '6',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/raja-ampat.jpg',
                    'imageable_id' => '7',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/raja-ampat-2.jpg',
                    'imageable_id' => '7',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/raja-ampat-3.jpg',
                    'imageable_id' => '7',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/mount-rinjani.jpg',
                    'imageable_id' => '8',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/mount-rinjani-2.jpg',
                    'imageable_id' => '8',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/mount-rinjani-3.jpg',
                    'imageable_id' => '8',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/mount-rinjani-4.jpg',
                    'imageable_id' => '8',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/mount-rinjani-5.jpg',
                    'imageable_id' => '8',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/mount-rinjani-6.jpg',
                    'imageable_id' => '8',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/banda-islands.jpg',
                    'imageable_id' => '9',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/banda-islands-2.jpg',
                    'imageable_id' => '9',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/banda-islands-3.jpg',
                    'imageable_id' => '9',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/banda-islands-4.jpg',
                    'imageable_id' => '9',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/jatiluwih-rice-terrace.jpg',
                    'imageable_id' => '10',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/jatiluwih-rice-terrace-2.jpg',
                    'imageable_id' => '10',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/jatiluwih-rice-terrace-3.jpg',
                    'imageable_id' => '10',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'attractions/jatiluwih-rice-terrace-4.jpg',
                    'imageable_id' => '10',
                    'imageable_type' => 'App\Models\Attraction',
                    'thumbnail' => false,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'cities/jakarta.jpg',
                    'imageable_id' => '1',
                    'imageable_type' => 'App\Models\City',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'cities/bali.jpg',
                    'imageable_id' => '3',
                    'imageable_type' => 'App\Models\City',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'cities/jogja.jpg',
                    'imageable_id' => '4',
                    'imageable_type' => 'App\Models\City',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'cities/makale.jpg',
                    'imageable_id' => '5',
                    'imageable_type' => 'App\Models\City',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'cities/pemantang-siantar.jpg',
                    'imageable_id' => '6',
                    'imageable_type' => 'App\Models\City',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'cities/waisai.jpg',
                    'imageable_id' => '7',
                    'imageable_type' => 'App\Models\City',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'cities/east-lombok.jpg',
                    'imageable_id' => '8',
                    'imageable_type' => 'App\Models\City',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'cities/central-maluku.jpg',
                    'imageable_id' => '9',
                    'imageable_type' => 'App\Models\City',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'categories/mountain.png',
                    'imageable_id' => '1',
                    'imageable_type' => 'App\Models\Category',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'categories/waterfall.png',
                    'imageable_id' => '2',
                    'imageable_type' => 'App\Models\Category',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'categories/museum.png',
                    'imageable_id' => '3',
                    'imageable_type' => 'App\Models\Category',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'categories/lake.png',
                    'imageable_id' => '4',
                    'imageable_type' => 'App\Models\Category',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'categories/recreation.png',
                    'imageable_id' => '5',
                    'imageable_type' => 'App\Models\Category',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'categories/fruits_garden.png',
                    'imageable_id' => '6',
                    'imageable_type' => 'App\Models\Category',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'categories/zoo.png',
                    'imageable_id' => '7',
                    'imageable_type' => 'App\Models\Category',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'categories/waterpark.png',
                    'imageable_id' => '8',
                    'imageable_type' => 'App\Models\Category',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'path' => 'categories/flowers_garden.png',
                    'imageable_id' => '9',
                    'imageable_type' => 'App\Models\Category',
                    'thumbnail' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        );
    }
}
